// =========================================================================================
//  SAYTNI BOSHQARISH PULTI (CONFIG)
// =========================================================================================

export const config = {
  // 1. SAYT HAQIDA MA'LUMOTLAR
  brandName: "Creative_designuz",
  subTitle: "Unutilmas Taklifnomalar",
  footerText: "Created by Creative_designuz",
  logoUrl: "/logo/l2.png",
  // 2. TELEGRAM SOZLAMALARI
  telegramLink: "https://t.me/+998993955537",

  // 3. VIDEOLAR RO'YXATI (High Quality, 9:16 Vertical, Stable Links)
  videos: [
    {
      id: 1,
      title: "Blue yulduz",
      image: "/image/i1.jpg",
      videoUrl: "/videos/v1.mp4",
    },
    {
      id: 2,
      title: "Oq Qora ",
      image: "/image/i2.jpg",
      videoUrl: "/videos/v2.mp4",
    },
    {
      id: 3,
      title: "Elegant Floral",
      image: "/image/i3.jpg",
      videoUrl: "/videos/v3.mp4",
    },
    {
      id: 4,
      title: "Elegant Gullar",
      image: "/image/i4.jpg",
      videoUrl: "/videos/v4.mp4",
    },
    {
      id: 5,
      title: "Oq binafsha",
      image: "/image/i5.jpg",
      videoUrl: "/videos/v5.mp4",
    },
    {
      id: 6,
      title: "Qizlar bazmi",
      image: "/image/i6.jpg",
      videoUrl: "/videos/v6.mp4",
    },
    {
      id: 7,
      title: "Yashil Go'zalik",
      image: "/image/i7.jpg",
      videoUrl: "/videos/v7.mp4",
    },
    {
      id: 8,
      title: "Nahorgi Osh",
      image: "/image/i8.jpg",
      videoUrl: "/videos/v8.mp4",
    },
    {
      id: 9,
      title: "Elegant BLue",
      image: "/image/i9.jpg",
      videoUrl: "/videos/v9.mp4",
    },
    {
      id: 10,
      title: "Nafis qizlar bazmi",
      image: "/image/i10.jpg",
      videoUrl: "/videos/v10.mp4",
    },
    {
      id: 11,
      title: "Rus tilida",
      image: "/image/i11.jpg",
      videoUrl: "/videos/v11.mp4",
    },
    {
      id: 12,
      title: "Classic Go'zalik",
      image: "/image/i12.jpg",
      videoUrl: "/videos/v12.mp4",
    },
    {
      id: 13,
      title: "Dizayn 13",
      image: "/image/i13.jpg",
      videoUrl: "/videos/v13.mp4",
    },
    {
      id: 14,
      title: "Dizayn 14",
      image: "/image/i14.jpg",
      videoUrl: "/videos/v14.mp4",
    },
    {
      id: 15,
      title: "Dizayn 15",
      image: "/image/i15.jpg",
      videoUrl: "/videos/v15.mp4",
    },
    {
      id: 16,
      title: "Dizayn 16",
      image: "/image/i16.jpg",
      videoUrl: "/videos/v16.mp4",
    },
    {
      id: 17,
      title: "Dizayn 17",
      image: "/image/i17.jpg",
      videoUrl: "/videos/v17.mp4",
    },
    {
      id: 18,
      title: "Dizayn 18",
      image: "/image/i18.jpg",
      videoUrl: "/videos/v18.mp4",
    },
    {
      id: 19,
      title: "Dizayn 19",
      image: "/image/i19.jpg",
      videoUrl: "/videos/v19.mp4",
    },
    {
      id: 20,
      title: "Dizayn 20",
      image: "/image/i20.jpg",
      videoUrl: "/videos/v20.mp4",
    },
    {
      id: 21,
      title: "Dizayn 21",
      image: "/image/i21.jpg",
      videoUrl: "/videos/v21.mp4",
    },
    {
      id: 22,
      title: "Dizayn 22",
      image: "/image/i22.jpg",
      videoUrl: "/videos/v22.mp4",
    },
    {
      id: 23,
      title: "Dizayn 23",
      image: "/image/i23.jpg",
      videoUrl: "/videos/v23.mp4",
    },
    {
      id: 24,
      title: "Dizayn 24",
      image: "/image/i24.jpg",
      videoUrl: "/videos/v24.mp4",
    },
    {
      id: 25,
      title: "Dizayn 25",
      image: "/image/i25.jpg",
      videoUrl: "/videos/v25.mp4",
    },
    {
      id: 26,
      title: "Dizayn 26",
      image: "/image/i26.jpg",
      videoUrl: "/videos/v26.mp4",
    },
    {
      id: 27,
      title: "Dizayn 27",
      image: "/image/i27.jpg",
      videoUrl: "/videos/v27.mp4",
    },
    {
      id: 28,
      title: "Dizayn 28",
      image: "/image/i28.jpg",
      videoUrl: "/videos/v28.mp4",
    },
    {
      id: 29,
      title: "Dizayn 29",
      image: "/image/i29.jpg",
      videoUrl: "/videos/v29.mp4",
    },
    {
      id: 30,
      title: "Dizayn 30",
      image: "/image/i30.jpg",
      videoUrl: "/videos/v30.mp4",
    },
    {
      id: 31,
      title: "Dizayn 31",
      image: "/image/i31.jpg",
      videoUrl: "/videos/v31.mp4",
    },
    {
      id: 32,
      title: "Dizayn 32",
      image: "/image/i32.jpg",
      videoUrl: "/videos/v32.mp4",
    },
    {
      id: 33,
      title: "Dizayn 33",
      image: "/image/i33.jpg",
      videoUrl: "/videos/v33.mp4",
    },
    {
      id: 34,
      title: "Dizayn 34",
      image: "/image/i34.jpg",
      videoUrl: "/videos/v34.mp4",
    },
    {
      id: 35,
      title: "Dizayn 35",
      image: "/image/i35.jpg",
      videoUrl: "/videos/v35.mp4",
    },
    {
      id: 36,
      title: "Dizayn 36",
      image: "/image/i36.jpg",
      videoUrl: "/videos/v36.mp4",
    },
    {
      id: 37,
      title: "Dizayn 37",
      image: "/image/i37.jpg",
      videoUrl: "/videos/v37.mp4",
    },
    {
      id: 38,
      title: "Dizayn 38",
      image: "/image/i38.jpg",
      videoUrl: "/videos/v38.mp4",
    },
    {
      id: 39,
      title: "Dizayn 39",
      image: "/image/i39.jpg",
      videoUrl: "/videos/v39.mp4",
    },
    {
      id: 40,
      title: "Dizayn 40",
      image: "/image/i40.jpg",
      videoUrl: "/videos/v40.mp4",
    },
    {
      id: 41,
      title: "Dizayn 41",
      image: "/image/i41.jpg",
      videoUrl: "/videos/v41.mp4",
    },
    {
      id: 42,
      title: "Dizayn 42",
      image: "/image/i42.jpg",
      videoUrl: "/videos/v42.mp4",
    },
    {
      id: 43,
      title: "Dizayn 43",
      image: "/image/i43.jpg",
      videoUrl: "/videos/v43.mp4",
    },
    {
      id: 44,
      title: "Dizayn 44",
      image: "/image/i44.jpg",
      videoUrl: "/videos/v44.mp4",
    },
    {
      id: 45,
      title: "Dizayn 45",
      image: "/image/i45.jpg",
      videoUrl: "/videos/v45.mp4",
    },
    {
      id: 46,
      title: "Dizayn 46",
      image: "/image/i46.jpg",
      videoUrl: "/videos/v46.mp4",
    },
    {
      id: 47,
      title: "Dizayn 47",
      image: "/image/i47.jpg",
      videoUrl: "/videos/v47.mp4",
    },
    {
      id: 48,
      title: "Dizayn 48",
      image: "/image/i48.jpg",
      videoUrl: "/videos/v48.mp4",
    },
  ],

  // 4. MUSIQALAR RO'YXATI (Stable Pixabay Links)
  music: [
    {
      id: 1,
      title: "Choli Qushi - Acoustic",
      duration: "0:35",
      author: "Turkish Vibe",
      url: "/music/choliQushi.m4a",
    },
    {
      id: 2,
      title: "Nadyr - Seni osmonimga olib ketaman",
      duration: "0:21",
      author: "Kel, deb aytolmasam netaman",
      url: "/music/ketDebHaydolmasa.m4a",
    },
    {
      id: 3,
      title: "Maher zain",
      duration: "0:17",
      author: "For The Rest Of My Life",
      url: "/music/meher.m4a",
    },
    {
      id: 4,
      title: "Sato - Torimning siri",
      duration: "0:22",
      author: "Osh Uchun",
      url: "/music/osh.m4a",
    },
    {
      id: 5,
      title: "Izzat Shukurov",
      duration: "0:38",
      author: "Oshiq bo'lar edim",
      url: "/music/oshiqBolarEdim.m4a",
    },
    {
      id: 6,
      title: "Jah Khalib",
      duration: "0:19",
      author: "Angela",
      url: "/music/tamDuragayaAngela.m4a",
    },
    {
      id: 7,
      title: "Izzat Shukurov",
      duration: "0:19",
      author: "Vafodorim",
      url: "/music/Vafodorim.m4a",
    },
    {
      id: 8,
      title: "Muhammad Al Muqit",
      duration: "2:59",
      author: "Wedding Nasheed",
      url: "/music/Mu.mp3",
    },
    {
      id: 9,
      title: "Alisher Uzoqov",
      duration: "3:17",
      author: "Oshiq yurak",
      url: "/music/AlisherUzoqov.mp3",
    },
  ],
};
