name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm ci

      - name: Install client dependencies (Tailwind, PostCSS)
        run: cd client && npm ci

      - name: Build
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 31.184.242.14
          username: gihub-deploy
          password: gM9aH7jD3c
          local-dir: dist/
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            api-server/public/videos/**
            api-server/public/image/**
            api-server/public/music/**
            api-server/public/data/**
            dist/webSites/**
